# Generated by Django 2.1.15 on 2020-01-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-name',)},
        ),
    ]
